In [20]:
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [22]:
%time rating_data = pd.read_csv('final_rating_data.csv',sep='\t',index_col=0,skiprows=100000,nrows=1000000)

CPU times: user 574 ms, sys: 0 ns, total: 574 ms
Wall time: 571 ms


In [23]:
array = rating_data.as_matrix()
X = array[:,:3]
y = array[:,4]

In [24]:
from sklearn.cross_validation import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((750000, 3), (250000, 3), (750000,), (250000,))

In [39]:
from sklearn.grid_search import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
n_neighbors_opt=list(range(500,1100,200))
weights_opt = ['uniform']
algorithm_opt = ['ball_tree']

In [40]:
param_grid = dict(n_neighbors= n_neighbors_opt,weights = weights_opt,algorithm = algorithm_opt)

In [41]:
grid = GridSearchCV(knn,param_grid,cv=10,n_jobs=-1,scoring='accuracy')

In [ ]:
%time grid.fit(X_train,y_train)

In [36]:
grid.best_score_

0.27894666666666668

In [37]:
y_pred = grid.predict(X_test)

In [52]:
#from sklearn.metrics import accuracy_score,confusion_matrix
#print(accuracy_score(y_pred,y_test))
#print(confusion_matrix(y_pred,y_test))

0.2686
[[   0    0    0    0    0    0    0    0    0    0]
 [   0   15    0    6    0   17    3   26    0    5]
 [   0    1    2    2    0    1    2    2    0    0]
 [   1    2    2    7    2   10    4   10    4    6]
 [   0    1    2    8    4    5    6   10    4    4]
 [ 118  247  103  546  297 1744  627 1715  397  855]
 [  22   38   34   94   90  242  259  366  177  111]
 [ 217  443  189  918  612 2913 1783 4148 1269 2200]
 [   2    3    3   13   20   44   50   60   57   37]
 [  19   51   18   90   51  248  127  518  162  479]]


In [38]:
grid.best_params_

{'algorithm': 'ball_tree', 'n_neighbors': 500, 'weights': 'uniform'}